# Generated by Django 4.1 on 2023-11-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
    ]
